# Generated by Django 3.2.23 on 2024-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('doubt', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'doubts',
                'managed': False,
            },
        ),
    ]
