# Generated by Django 3.2.23 on 2024-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'progress',
                'managed': False,
            },
        ),
    ]
